# ------------------------------------------------------------------------------------------------------------------------
# This action will make a COPY of this repo in another destination repo, currently on-demand only
# ------------------------------------------------------------------------------------------------------------------------
# These commands work at my command line...
#  > git remote add destination https://<insert-pat-here>@github.com/lluppes/test-sync-repo.git
#  > git push destination main -f
#  > git remote remove destination
# ------------------------------------------------------------------------------------------------------------------------
# To configure this, set the following variables in your GitHub environment or repo settings:
#   1. Create a variable named SYNC_DESTINATION_ORG_NAME 
#   2. Create a variable named SYNC_DESTINATION_REPO_NAME
#   3. Go into your target repo settings and create a Personal Access Token (PAT) with repo permissions
#   4. Create a secret named SYNC_DESTINATION_PAT
#   Sample Commands:
#     gh variable set SYNC_DESTINATION_ORG_NAME -b your-target-org-name
#     gh variable set SYNC_DESTINATION_REPO_NAME -b your-target-repo-name
#     gh variable set SYNC_DESTINATION_USER_EMAIL -b your-email@example.com
#     gh variable set SYNC_DESTINATION_USER_NAME -b your-user-name
#     gh secret set SYNC_DESTINATION_PAT -b your-personal-access-token
# ------------------------------------------------------------------------------------------------------------------------
# References:
#   https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173
#   https://www.howtogeek.com/devops/how-to-use-git-with-multiple-remote-repositories/
# ------------------------------------------------------------------------------------------------------------------------
name: 99.sync.repo
run-name: '99 - Sync to destination repo by @${{ github.actor }}'

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
          path: main

      - name: Display Variables and Files
        run: |-
          echo "Original Repo Name: ${{ github.event.repository.name }}"
          echo "Sync Destination Org Name: ${{ vars.SYNC_DESTINATION_ORG_NAME }}"
          echo "Sync Destination Repo Name: ${{ vars.SYNC_DESTINATION_REPO_NAME }}"
          echo "---------------------------------"
          echo "##[group]Directory of ${{ github.workspace }}"
          tree -R ${{ github.workspace }}
          echo "##[endgroup]"
        continue-on-error: true
                
      - name: Push to destination repository
        run: |
          git config --global user.email "${{ vars.SYNC_DESTINATION_USER_EMAIL }}"
          git config --global user.name "${{ vars.SYNC_DESTINATION_USER_NAME }}"

          echo "Run: cd main"
          cd main

          echo "Run: git remote add destination https://${{ secrets.SYNC_DESTINATION_PAT }}@github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git"
          git remote add destination https://${{ secrets.SYNC_DESTINATION_PAT }}@github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git

          echo "Run: git push destination main -f"
          git push destination main -f
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_DESTINATION_PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORIGINAL_ORG_NAME: ${{ github.event.repository.owner.login }}

# echo "Run: git remote add destination https://github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ github.event.repository.name }}.git"
# git remote add destination https://github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ github.event.repository.name }}.git

# echo "Run: git remote set-url --add --push origin git://${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git"
# git remote set-url --add --push origin git://${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git

# echo "Run: git remote add destination ${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ github.event.repository.name }}.git"
# git remote add destination ${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ github.event.repository.name }}.git

# echo "Run: cd ${{ github.workspace }}/${{ github.event.repository.name }}
# cd ${{ github.workspace }}/${{ github.event.repository.name }}

# git clone https://${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git
# git clone https://github.com/${{ env.ORIGINAL_ORG_NAME }}/${{ github.event.repository.name }}.git
