# ------------------------------------------------------------------------------------------------------------------------
# This action will make a COPY of this repo in another destination repo, currently on-demand only
# ------------------------------------------------------------------------------------------------------------------------
# To configure this, set the following variables in your GitHub environment or repo settings:
#   1. Create a variable named SYNC_DESTINATION_ORG_NAME 
#   2. Create a variable named SYNC_DESTINATION_REPO_NAME
#   3. Go into your target repo settings and create a Personal Access Token (PAT) with repo permissions
#   4. Create a secret named SYNC_DESTINATION_PAT
#   Sample Commands:
#     gh variable set SYNC_DESTINATION_ORG_NAME -b your-target-org-name
#     gh variable set SYNC_DESTINATION_REPO_NAME -b your-target-repo-name
#     gh secret set SYNC_DESTINATION_PAT -b your-personal-access-token
# ------------------------------------------------------------------------------------------------------------------------
# Reference: https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173
# ------------------------------------------------------------------------------------------------------------------------
name: 99.sync.repo
run-name: '99 - Sync to destination repo by @${{ github.actor }}'

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "your email"
          git config --global user.name "your user name"

          echo Run: git clone https://github.com/${{ env.ORIGINAL_ORG_NAME }}:${{ secrets.SYNC_SOURCE_PAT }}@${{ env.ORIGINAL_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git clone https://github.com/${{ env.ORIGINAL_ORG_NAME }}:${{ secrets.SYNC_SOURCE_PAT }}@${{ env.ORIGINAL_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          
          echo Run: cd ${{ env.ORIGINAL_REPO_NAME }}
          cd ${{ env.ORIGINAL_REPO_NAME }}

          echo Run: git remote add ${{ env.ORIGINAL_REPO_NAME }} https://github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@github.com/github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@github.com/github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git

          echo Run: git remote update
          git remote update

          echo Run: git merge ${{ env.ORIGINAL_REPO_NAME }}/main
          git merge ${{ env.ORIGINAL_REPO_NAME }}/main

          echo Run: git push origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_DESTINATION_PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORIGINAL_ORG_NAME: ${{ github.event.repository.owner.login }}

# git clone https://${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git
# git clone https://github.com/${{ env.ORIGINAL_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
