# ------------------------------------------------------------------------------------------------------------------------
# This action will make a COPY of this repo in another destination repo, currently on-demand only
# ------------------------------------------------------------------------------------------------------------------------
# To configure this, set the following variables in your GitHub environment or repo settings:
#   1. Create a variable named SYNC_DESTINATION_ORG_NAME 
#   2. Create a variable named SYNC_DESTINATION_REPO_NAME
#   3. Go into your target repo settings and create a Personal Access Token (PAT) with repo permissions
#   4. Create a secret named SYNC_DESTINATION_PAT
#   Sample Commands:
#     gh variable set SYNC_DESTINATION_ORG_NAME -b your-target-org-name
#     gh variable set SYNC_DESTINATION_REPO_NAME -b your-target-repo-name
#     gh secret set SYNC_DESTINATION_PAT -b your-personal-access-token
# ------------------------------------------------------------------------------------------------------------------------
# Reference: https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173
# ------------------------------------------------------------------------------------------------------------------------
name: 99.sync.repo
run-name: '99 - Sync to destination repo by @${{ github.actor }}'

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
          path: main

      - name: Display Variables and Files
        run: |-
          echo "env.generatedAppEnvName=${{ env.generatedAppEnvName }}"
          echo "Original Repo Name: ${{ github.event.repository.name }}"
          echo "Sync Destination Org Name: ${{ vars.SYNC_DESTINATION_ORG_NAME }}"
          echo "Sync Destination Repo Name: ${{ vars.SYNC_DESTINATION_REPO_NAME }}"
          echo "---------------------------------"
          echo "##[group]Directory of ${{ github.workspace }}"
          tree -R ${{ github.workspace }}
          echo "##[endgroup]"
        continue-on-error: true
                
      - name: Push to destination repository
        run: |
          git config --global user.email "your email"
          git config --global user.name "your user name"

          echo ##[command] cd main
          cd main

          echo ##[command] git remote add origin https://${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@https://github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ github.event.repository.name }}.git
          git remote add origin https://${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@https://github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ github.event.repository.name }}.git

          echo ##[command] git push origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_DESTINATION_PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORIGINAL_ORG_NAME: ${{ github.event.repository.owner.login }}

          # echo ##[command] cd ${{ github.workspace }}/${{ github.event.repository.name }}
          # cd ${{ github.workspace }}/${{ github.event.repository.name }}
# git clone https://${{ vars.SYNC_DESTINATION_ORG_NAME }}:${{ secrets.SYNC_DESTINATION_PAT }}@github.com/${{ vars.SYNC_DESTINATION_ORG_NAME }}/${{ vars.SYNC_DESTINATION_REPO_NAME }}.git
# git clone https://github.com/${{ env.ORIGINAL_ORG_NAME }}/${{ github.event.repository.name }}.git
